# Generated by Django 4.0.1 on 2022-01-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=30)),
                ('last', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=11)),
            ],
        ),
    ]
