# Generated by Django 3.2 on 2022-04-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c2_main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='consultation_appt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appt_datetime', models.DateTimeField(unique=True)),
            ],
        ),
    ]
